package com.serg_tito.jdbs.starter;

import org.postgresql.Driver;
import com.serg_tito.jdbs.starter.util.ConnectionManager;

import java.sql.SQLException;
import java.sql.Statement;

public class JDBCRunner {
    public static void main(String[] args) throws SQLException {

        Class<Driver> driverClass = Driver.class;
        String sql = """
                INSERT INTO info(data)
                VALUES 
                ('autogenerated')
                """;
        try (var connection = ConnectionManager.open();
             var statement = connection.createStatement()) {
            System.out.println(connection.getSchema());
            System.out.println(connection.getTransactionIsolation());
            var executeResult = statement.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);
            var generatedKeys = statement.getGeneratedKeys();
            if (generatedKeys.next()){
                var generatedId = generatedKeys.getInt("id");
                System.out.println(generatedId);
            }
        }

    }
}
